SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `Administrator`; -- remove at next update
DROP TABLE IF EXISTS `Ban`;
DROP TABLE IF EXISTS `Favorite`;
DROP TABLE IF EXISTS `Login`;
DROP TABLE IF EXISTS `LoginAttempt`;
DROP TABLE IF EXISTS `Message`;
DROP TABLE IF EXISTS `Moderator`; -- remove at next update
DROP TABLE IF EXISTS `Picture`;
DROP TABLE IF EXISTS `Recipe`;
DROP TABLE IF EXISTS `RecipeType`;
DROP TABLE IF EXISTS `Comment`;
DROP TABLE IF EXISTS `Report`;
DROP TABLE IF EXISTS `Step`;
DROP TABLE IF EXISTS `User`;
SET FOREIGN_KEY_CHECKS = 1;